name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check
        run: /bin/bash -c "echo $ANDROID_HOME"

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"
